/* AUTO-GENERATED by tools/gen_ville_assets.py — do not edit. */
#ifndef __VILLE_SPRITES_H__
#define __VILLE_SPRITES_H__
#include "lvgl.h"

#define VILLE_SPRITE_PX    10
#define VILLE_NUM_PERSONA  2
#define VILLE_NUM_DIR      4
#define VILLE_WALK_FRAMES  3
/* dir 枚举: 0=down 1=left 2=right 3=up (与生成器 DIR_ORDER 对齐) */
typedef enum { VILLE_DOWN=0, VILLE_LEFT=1, VILLE_RIGHT=2, VILLE_UP=3 } ville_dir_t;
extern const lv_image_dsc_t *ville_sprite[VILLE_NUM_PERSONA][VILLE_NUM_DIR][VILLE_WALK_FRAMES];
#endif
