/* AUTO-GENERATED by tools/gen_ville_assets.py — do not edit. */
#ifndef __VILLE_TRACK_H__
#define __VILLE_TRACK_H__
#include <stdint.h>

#define VILLE_NUM_PERSONA  2
#define VILLE_NUM_STEPS    247
#define VILLE_SEC_PER_STEP 10
#define VILLE_STEP_MS      600
extern const int16_t *ville_track_x[VILLE_NUM_PERSONA];
extern const int16_t *ville_track_y[VILLE_NUM_PERSONA];
#endif
