/* AUTO-GENERATED by tools/gen_ville_assets.py — do not edit. */
#ifndef __VILLE_MAP_H__
#define __VILLE_MAP_H__
#include "lvgl.h"

#define VILLE_MAP_W        700
#define VILLE_MAP_H        510
#define VILLE_TILE_PX      10
#define VILLE_REGION_X0    58
#define VILLE_REGION_Y0    14
extern const lv_image_dsc_t ville_map_dsc;
#endif
